// GENERATED by `cargo xtask gen-types` from crates/api-types. Do not edit.
/* eslint-disable */

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null;

export type Score = { "kind": "cp", "value": number } | { "kind": "mate", "value": number };

export type Side = "white" | "black";

export type Phase = "opening" | "middlegame" | "endgame";

export type Classification = "book" | "best" | "excellent" | "good" | "inaccuracy" | "mistake" | "blunder" | "missed_win";

export type Judgement = "inaccuracy" | "mistake" | "blunder";

export type Opening = { eco: string, name: string, };

export type PlyMove = { 
/**
 * 1-based ply index within the game.
 */
ply: number, mover: Side, san: string, uci: string, fen_before: string, fen_after: string, clock_ms: number | null, 
/**
 * White-POV `[%eval]` found in the PGN after this move (Lichess exports).
 */
pgn_eval: Score | null, 
/**
 * First move-assessment NAG (1..=6) attached to this move.
 */
nag: number | null, };

export type GameAccuracy = { white: number | null, black: number | null, };

export type EloTier = "beginner" | "intermediate" | "advanced" | "expert";

export type Limit = { depth: number | null, movetime_ms: number | null, nodes: number | null, };

export type Terminal = "checkmate" | "stalemate";

export type LineDto = { rank: number, depth: number, 
/**
 * White POV.
 */
score: Score, wdl: [number, number, number] | null, pv_uci: Array<string>, pv_san: Array<string>, };

export type EngineAnalysis = { fen: string, depth: number, lines: Array<LineDto>, nodes: number, nps: number, time_ms: number, terminal: Terminal | null, done: boolean, engine: string, };

export type EngineEvent = { "type": "update", analysis: EngineAnalysis, } | { "type": "done", analysis: EngineAnalysis, } | { "type": "error", message: string, };

export type GameSource = "pgn" | "fen" | "lichess" | "chesscom";

export type JobStatus = "queued" | "running" | "done" | "failed" | "cancelled";

export type GameSummary = { id: string, source: GameSource, source_id: string | null, white: string, black: string, white_elo: number | null, black_elo: number | null, result: string, date: string | null, time_control: string | null, eco: string | null, opening: string | null, 
/**
 * Which side the app's user played, when known.
 */
user_side: Side | null, ply_count: number, analysis_status: JobStatus | null, white_accuracy: number | null, black_accuracy: number | null, imported_at: number, };

export type GameDetail = { summary: GameSummary, pgn: string, start_fen: string, moves: Array<PlyMove>, analysis: GameAnalysis | null, };

export type MoveEval = { ply: number, mover: Side, san: string, uci: string, 
/**
 * White-POV eval of the position after this move.
 */
score: Score, depth: number, 
/**
 * Engine's choice in the position before the move.
 */
best_uci: string | null, best_san: string | null, best_line_san: Array<string>, classification: Classification, lichess_judgement: Judgement | null, 
/**
 * Mover's win% before and after (0..100).
 */
win_before: number, win_after: number, delta_wc: number, accuracy: number, phase: Phase, is_key_moment: boolean, };

export type BetterMove = { san: string, line_san: Array<string>, reason: string, };

export type VerificationStatus = "ok" | "partial" | "unverified";

export type Verification = { status: VerificationStatus, issues: Array<string>, 
/**
 * SAN moves the text mentions that are legal but not in any engine line.
 */
unverified_moves: Array<string>, 
/**
 * SAN moves that are illegal or invented (removed where possible).
 */
rejected_moves: Array<string>, };

export type Explanation = { ply: number, headline: string, why_it_matters: string, better_move: BetterMove | null, concept_tags: Array<string>, takeaway: string, mentioned_moves: Array<string>, verification: Verification, provider: string, model: string, };

export type GameReview = { text: string, themes: Array<string>, verification: Verification, };

export type GameAnalysis = { id: string, game_id: string, status: JobStatus, elo: number, tier: EloTier, user_side: Side | null, engine: string, 
/**
 * White-POV eval of the starting position.
 */
start_score: Score | null, white_accuracy: number | null, black_accuracy: number | null, moves: Array<MoveEval>, key_moments: Array<number>, explanations: Array<Explanation>, review: GameReview | null, error: string | null, created_at: number, };

export type AnalyseGameRequest = { 
/**
 * Explain for this rating; defaults to the user's setting.
 */
elo: number | null, user_side: Side | null, 
/**
 * Ask the LLM to explain key moments (needs a provider).
 */
explain: boolean, 
/**
 * Discard any previous analysis and start over.
 */
force: boolean, };

export type AnalyseGameResponse = { analysis_id: string, status: JobStatus, };

export type JobStage = "engine" | "deep_pass" | "explaining" | "review";

export type JobEvent = { "type": "snapshot", analysis: GameAnalysis, } | { "type": "progress", stage: JobStage, done: number, total: number, } | { "type": "move", eval: MoveEval, } | { "type": "accuracy", white: number | null, black: number | null, } | { "type": "key_moments", plies: Array<number>, } | { "type": "explanation_started", ply: number, } | { "type": "explanation", explanation: Explanation, } | { "type": "explanation_failed", ply: number, message: string, } | { "type": "review", review: GameReview, } | { "type": "done", analysis: GameAnalysis, } | { "type": "error", message: string, };

export type ImportRequest = { "source": "pgn", pgn: string, } | { "source": "fen", fen: string, } | { "source": "lichess_game", id: string, } | { "source": "lichess", username: string, max: number | null, } | { "source": "chesscom", username: string, max: number | null, };

export type ImportResponse = { games: Array<GameSummary>, 
/**
 * Games already imported before.
 */
duplicates: number, errors: Array<string>, };

export type ChatRole = "user" | "assistant";

export type ToolCallView = { id: string, name: string, input: JsonValue, summary: string, is_error: boolean, 
/**
 * Structured result for the board (engine lines, played line).
 */
data: unknown, };

export type ChatMessage = { id: string, role: ChatRole, text: string, tool_calls: Array<ToolCallView>, verification: Verification | null, fen: string | null, ply: number | null, created_at: number, };

export type ChatThread = { id: string, game_id: string | null, title: string, created_at: number, updated_at: number, };

export type ChatThreadDetail = { thread: ChatThread, messages: Array<ChatMessage>, };

export type CreateThreadRequest = { game_id: string | null, title: string | null, };

export type SendMessageRequest = { text: string, 
/**
 * Board position the question is about.
 */
fen: string, ply: number | null, 
/**
 * SAN moves from the game start to `fen`, when on a game.
 */
move_path: Array<string>, elo: number | null, };

export type ChatEvent = { "type": "user_message", message: ChatMessage, } | { "type": "text_delta", text: string, } | { "type": "thinking", text: string, } | { "type": "tool_call", id: string, name: string, input: JsonValue, } | { "type": "tool_result", call: ToolCallView, } | { "type": "verification", verification: Verification, } | { "type": "done", message: ChatMessage, } | { "type": "error", message: string, };

export type ProviderKind = "anthropic" | "openai" | "openrouter" | "ollama" | "openai_compatible";

export type Provider = { id: string, kind: ProviderKind, label: string, base_url: string, model: string, has_key: boolean, is_default: boolean, };

export type ProviderInput = { kind: ProviderKind, label: string | null, base_url: string | null, model: string | null, 
/**
 * `None` keeps the stored key on update; empty string clears it.
 */
api_key: string | null, is_default: boolean, };

export type ProviderTestResult = { ok: boolean, message: string, latency_ms: number, };

export type Settings = { elo: number, lichess_username: string | null, chesscom_username: string | null, 
/**
 * Allow calls to the Lichess opening explorer (needs a Lichess token).
 */
explorer_enabled: boolean, 
/**
 * A Lichess personal API token is stored. Lichess requires one for
 * username game export and the opening explorer.
 */
has_lichess_token: boolean, };

export type SettingsInput = { elo: number, lichess_username: string | null, chesscom_username: string | null, explorer_enabled: boolean, 
/**
 * `None` keeps the stored token; empty string clears it.
 */
lichess_token: string | null, };

export type Meta = { version: string, engine: string, engine_threads: number, engine_workers: number, mode: string, has_provider: boolean, 
/**
 * The site operator supplies the AI model; users never configure keys.
 */
managed_provider: boolean, 
/**
 * e.g. "Claude (claude-opus-5)" when managed.
 */
provider_label: string | null, 
/**
 * Today's share of the site's AI budget already used, 0..1, when capped.
 */
budget_used: number | null, };

export type ApiError = { error: string, };

