[package]
name = "engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
ts = ["dep:ts-rs", "chess-core/ts"]

[dependencies]
chess-core.workspace = true
shakmaty.workspace = true
tokio.workspace = true
tokio-util.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
lru.workspace = true
async-trait.workspace = true
ts-rs = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
